### PR TITLE
Update color.py

### PR DESCRIPTION
**Pull request by tieugene**
Salt is salty

### CODE REVIEW

**Comment by romanlv** [comment]
thanks!

**Comment by tieugene** [comment]
You're welcome.
I'm planning to add some tags:
- registerTTFont, registerFontFamily (ready)
- transform (ready)
- letterBoxes + boxStyle (in process)
- barCodeFlowable

Will you accept them?
PS: you can mailto:ti.eugene@gmail.com directly

**Comment by romanlv** [comment]
Why not? sounds like useful features. Do you need those extra features yourself?
Are you interested in becoming a maintainer? I do not really have a vision for future development ... existing functionality works fine for my case

**Comment by tieugene** [comment]
> Do you need those extra features yourself?

Yes. There are many OCR-oriented blanks (like [this one](http://archive.mid.ru//bul_ns_en.nsf/uvedomlenie.pdf)).

> Are you interested in becoming a maintainer?

Yes. I'd like to make trml2pdf as original rml2pdf-compatible as possible - to provide most of RML [features](http://www.reportlab.com/software/rml-reference/).
And make CentOS/Fedora packages for this (as Fedora [maintainer](https://admin.fedoraproject.org/pkgdb/packager/tieugene/))

Please contact me [directly](mailto:ti.eugene@gmail.com) because discussing via Issues is not comfortable.

**Pull request merged**
