### PR TITLE
Python 3.4 compatibility, <ul>/<li> support, QR barcode support

### PR DESCRIPTION
**Pull request by willson556**
Added a couple of features as described in the title and adopts PEP8 formatting rules. Also includes @edwardoliveira's changes. Used six to make the code backwards compatible with python2.7. Test suite runs under python 3.4 and 2.7.

### CODE REVIEW

**Comment by romanlv** [comment]
released as v0.3 on pypi

**Comment by romanlv** [comment]
thank you

**Comment by willson556** [comment]
No problem; needed it for a project. Thanks for the great start!

**Comment by edwardoliveira** [comment]
@willson556 Thank you _very much_ for incorporating my little snippets! :) :100: 

@romanlv Thanks for releasing v0.3 on pypi. Great project! :+1:

**Pull request merged**
