### PR TITLE
A couple of bug fixes

### PR DESCRIPTION
**Pull request by edwardoliveira**
8ef81de - update the gitignore, by adding more files

b89394a - we had trouble dealing with UTF-8 chars (as far as I remember). This trick fixed the problem. Please, review this change carefully before applying (IF you decide to apply)

d99276e - if the XML string had spaces at beginning it generated an error during parsing. A simple trim solved that.

b77ae26 - We had trouble also generating barcode on Python3. This fix solved it.

### CODE REVIEW

**Comment by romanlv** [comment]
@edwardoliveira, thanks for the pull request
there is a problem with `text_type` though, it's not even imported anywhere in the code:
just run `tox`
returns `NameError: name 'text_type' is not defined`

For other problems you mentioned, is it possible to add a quick unit test to make sure that it continues to work in different versions of python?

**Comment by edwardoliveira** [comment]
Sorry for the late response. Sure, gonna add the unit tests and fix the `text_type` asap. Thanks for the feedback! :)

**Comment by romanlv** [comment]
Thanks, uploaded to pypi as `0.4.2`

**Comment by edwardoliveira** [comment]
Thanks and sorry for the (really) late response! :+1: Still need to work on more unit tests, so it should be my next contrib to the project, I hope. :smiley:

**Pull request merged**
